# Generated by Django 5.2.7 on 2025-11-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BreakScheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(default=1175, max_length=5),
            preserve_default=False,
        ),
    ]
